In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets

In [3]:
df=pd.read_csv("Summary of Weather.csv")

/tmp/ipykernel_3162/756480173.py:1: DtypeWarning: Columns (7,8,18,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("Summary of Weather.csv")


In [4]:
df

STA        Date Precip  WindGustSpd    MaxTemp    MinTemp  \
0       10001    1942-7-1  1.016          NaN  25.555556  22.222222   
1       10001    1942-7-2      0          NaN  28.888889  21.666667   
2       10001    1942-7-3   2.54          NaN  26.111111  22.222222   
3       10001    1942-7-4   2.54          NaN  26.666667  22.222222   
4       10001    1942-7-5      0          NaN  26.666667  21.666667   
...       ...         ...    ...          ...        ...        ...   
119035  82506  1945-12-27      0          NaN  28.333333  18.333333   
119036  82506  1945-12-28  9.906          NaN  29.444444  18.333333   
119037  82506  1945-12-29      0          NaN  28.333333  18.333333   
119038  82506  1945-12-30      0          NaN  28.333333  18.333333   
119039  82506  1945-12-31      0          NaN  29.444444  17.222222   

         MeanTemp Snowfall PoorWeather  YR  ...  FB  FTI ITH  PGT  TSHDSBRSGF  \
0       23.888889      0.0         NaN  42  ... NaN  NaN NaN  NaN         NaN   
1       25.555556      0.0         NaN  42  ... NaN  NaN NaN  NaN         NaN   
2       24.444444      0.0         NaN  42  ... NaN  NaN NaN  NaN         NaN   
3       24.444444      0.0         NaN  42  ... NaN  NaN NaN  NaN         NaN   
4       24.444444      0.0         NaN  42  ... NaN  NaN NaN  NaN         NaN   
...           ...      ...         ...  ..  ...  ..  ...  ..  ...         ...   
119035  23.333333      0.0         NaN  45  ... NaN  NaN NaN  NaN         NaN   
119036  23.888889      0.0         1.0  45  ... NaN  NaN NaN  NaN         1.0   
119037  23.333333      0.0         1.0  45  ... NaN  NaN NaN  NaN         1.0   
119038  23.333333      0.0         NaN  45  ... NaN  NaN NaN  NaN         NaN   
119039  23.333333      0.0         NaN  45  ... NaN  NaN NaN  NaN         NaN   

        SD3  RHX  RHN RVG  WTE  
0       NaN  NaN  NaN NaN  NaN  
1       NaN  NaN  NaN NaN  NaN  
2       NaN  NaN  NaN NaN  NaN  
3       NaN  NaN  NaN NaN  NaN  
4       NaN  NaN  NaN NaN  NaN  
...     ...  ...  ...  ..  ...  
119035  NaN  NaN  NaN NaN  NaN  
119036  NaN  NaN  NaN NaN  NaN  
119037  NaN  NaN  NaN NaN  NaN  
119038  NaN  NaN  NaN NaN  NaN  
119039  NaN  NaN  NaN NaN  NaN  

[119040 rows x 31 columns]

In [4]:
iris["feature_names"]

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
y = (iris["target"] == 2).astype(np.int)

/tmp/ipykernel_5726/3764238078.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = (iris["target"] == 2).astype(np.int)


In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
log_reg = LogisticRegression()
log_reg.fit(x, y)

LogisticRegression()

In [9]:
x_new = np.linspace(0, 3, 1000).reshape(-1, 1)
y_proba = log_reg.predict_proba(x_new)

In [18]:
y_proba

array([[9.99250016e-01, 7.49984089e-04],
       [9.99240201e-01, 7.59799387e-04],
       [9.99230257e-01, 7.69743043e-04],
       ...,
       [3.08374822e-03, 9.96916252e-01],
       [3.04400296e-03, 9.96955997e-01],
       [3.00476842e-03, 9.96995232e-01]])

In [20]:
log_reg.predict(x_new)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [17]:
for i in y_proba:
    if(i[1]>=0.5):
        print("Virgin bitch")
    else:
        print("Chudh gayi")

Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi
Chudh gayi